---
name: Basic Commands
on:
  push:
    branches: -main
jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: termurin
          java-version: "17"
      - name: Compile Java Programs
        run: javac hello.java
      - name: run hello
